services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    restart: always
    ports:
      - ${RABBIT_PORT}:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - proxy_network

  sender:
    build: .
    container_name: sender
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - proxy_network
    environment:
      - TZ=America/Sao_Paulo
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Sao_Paulo
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  rabbitmq_data:

networks:
  proxy_network:
    external: true